### ISSUE TITLE
Plugin Usage 

### ISSUE THREAD

**Issue by williamrizqallah** [CodeBradley/contact-form-7-rest-api#1]
Is It Ready To Use This Plugin If Yes Please Let Me Know How It Works
Thanks

**Comment by CodeBradley** [comment]
Most of this plugin should work, it has not been fully tested though so I'm sure there are some bugs; most likely related to mail_2 settings and a small chance it may have auth issues.

All you need to do is install it and you can use it just like the rest of the Rest API. The endpoints are listed in the readme and the schema in the code. 

I wasn't sure if there would be any interest in this so I pushed it without much testing. If you send me any issues you find then I'll be glad to update it, I just haven't had the time. I'll also look through it again and update the Readme so its more user friendly.

**Comment by CodeBradley** [comment]
Looking over this again, I wouldn't use it just yet unless you really need to. I'm going to have to rename a lot of stuff in the schema and I think it will break anything you make if the plugin ever gets updated. If you do use it, I wouldn't update it to the latest version until you have time to redo your code.

I did add a bunch of TODO's discussing the issues for anyone who is interested in contributing to this.

**Comment by finis-intrinsic** [comment]
Hi great Thanks for making this plugin.
I am using angular 2 for front end
I just activated this plugin but still after going through the end points i cant see the forms which is created. Pls help

**Comment by CodeBradley** [comment]
@kamlesh-astech 

It's very important that you are authenticated before you can use this plugin. Since we don't want anyone to come along and view the forms saved in the database it is required that you have the capability to edit other users posts before you can view or modify the saved forms.

With OAuth authentication you will be able to create a client that will have all of the same capabilities as an administrator which will then allow you to access the forms via the Rest API using the endpoints in the readme.

http://v2.wp-api.org/guide/authentication/#oauth-authentication

Also, as I mentioned previously, the schema needs to be recreated so you may run into some minor issues, but overall the plugin should work. I plan on updating this as soon as possible but I've just been to busy lately

**Comment by CodeBradley** [comment]
**Important Note:** Endpoints are now included with the Contact Form 7 plugin as of version 4.7. I only recommend working with this code if you are using an older version of Contact Form 7.

Here's the changelog: https://contactform7.com/2017/03/03/contact-form-7-47/

**Comment by finis-intrinsic** [comment]
Thanks for the plugin update @CodeBradley
